### ISSUE TITLE
Something wrong with "Texlive" updated to 2023

### ISSUE THREAD

**Issue by jiangshen95** [ivaquero/scoopet#83]
It seems it doesn't be installed successfully. Very few files in the "texlive/2023“ directory, and it doesn't work.

I am not sure it's my problem, or something wrong with the bucket. "Scoop" tells me everything is OK.

**Comment by ivaquero** [comment]
Hi, I checked the texlive.json, and found there was no error. This manifest uses a easy-installer [install-tl.zip](https://mirrors4.tuna.tsinghua.edu.cn/ctan/systems/texlive/tlnet/install-tl.zip). After extracted, this installer will downloaded pkgs using curl in the background and it takes a longer time since texlive is of big size.

**Comment by jiangshen95** [comment]
I think there may have been some network instability during the download of texlive, which resulted in incomplete package downloads. Reinstalling should solve the issue. Thank you.

**Comment by ivaquero** [comment]
> I think there may have been some network instability during the download of texlive, which resulted in incomplete package downloads. Reinstalling should solve the issue. Thank you.

You're welcome.
